before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: mZv4B5duZXazkjduR883qScqlaHskZJU10nUYFDZn/inB5j33nmt9YzYQL3tdWpG6EUQpe4v0GZ8BloVPBs8x+10C8Rs2o4icnjaOsKf1uGBSFIfVlRztW6XRC4yiOrnuLveL1gz7siK32h8ey0G+xjCFFjTjn9jRwQvoBtaSipvCdNDV0uSZ6GpIid49ePaXU9n5hd3glIzg6hR/pkdOzUWsY7b6qEu43/JSf5fQY4UAWVpzS9nh61vatYaT29w4AamZ8cwdygEh5BXT67jXDW4jC25h4NIdMYAu4uggMNDkcydojZreHsFZZtOuhVQnvl6hJ8MA1CrH3U+Uj6cL7CsJPRkmy1T/RX25pxMxq8p+c9xJVK6PbgoTMLWndyu/3iGCwv0YNKR2QGbB/iJH2iDwWAXhP6gt1wJJr02baHkz2XLlJQOyvpHlLRXGC8LxVhb5Svzd6NxqUoWJL6tjMbJDMEEPyXxgvJxDynVvw7tTBTuxBWQScrbtaZqDQwGfJoy1pSRJc9+yHPYM5GJ5kyTMVWYnMasVsM5T8KXo8lDxfvjyHeIh+1yCim6KuiZnPqB4y7XNUZMdwPHhlkmCrredKDk81+YMRJ0m1uHb2WCwlUUu8FtTFnGsHNS8cKOP6437B0VagbPnfC6bTHJ9HHT2GL0eTKIg83nJw3JrFU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
